[project]
name = "rec-sys-feast-edb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.14"
dependencies = [
    "feast[postgres]==0.48.1",
    "jupyter>=1.1.1",
    "torch>=2.6.0",
]
